//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHSM.HB.ObjSapForRemoting.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_petrochinaZP10PSIF013_PO_ZP10PSIF013_POService {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_petrochinaZP10PSIF013_PO_ZP10PSIF013_POService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_PO_ZP10PSIF013_POService {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_PO_ZP10PSIF013_POService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_LFA1_ZP10PSIF013_LFA1Service {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_LFA1_ZP10PSIF013_LFA1Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_MARA_ZP10PSIF013_MARAService {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_MARA_ZP10PSIF013_MARAService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_PSDG079_ZP10PSIF013_PSDG079Service {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_PSDG079_ZP10PSIF013_PSDG079Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_QTZSL_ZP10PSIF013_QTZSLService {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_QTZSL_ZP10PSIF013_QTZSLService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_PRPS_ZP10PSIF013_PRPSService {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_PRPS_ZP10PSIF013_PRPSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ep.erp.petrochina:8160/sap/bc/soap/rfc")]
        public string LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_COVP_ZP10PSIF013_COVPService {
            get {
                return ((string)(this["LHSM_WRI_ObjSapForRemoting_Sap_ZP10PSIF013_COVP_ZP10PSIF013_COVPService"]));
            }
        }
    }
}
